[package]
name = "scaffold"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.3"
cranelift = "0.80.0"
cranelift-object = "0.80.0"
cranelift-module = "0.80.0"